Cerezoac94/EKAAShop

README.md
Actualizacion de mi informacion individual y cambios descripcion de los 'types' en el readme.
=> docs(readme): Update readme set author info and update desc types

README.md
=> docs(readme): Update name autor readme

api/src/db/db.js
Creacion de archivo db y conexion de la base de datos
=> add(db file): Create db file and connection

api/src/db/db.js, api/src/models/index.js, api/src/models/product/Product.js, api/src/server.js
Creacion de modelo de la tabla de producto
=> add(api-models): Create Model Product

client/package-lock.json, client/package.json, client/src/App.jsx, client/src/components/header/Header.jsx, client/src/main.jsx, client/src/styles/abstracts/_variables.scss, client/src/styles/base/_base.scss, client/src/styles/base/_reset.scss, client/src/styles/components/_header.scss, client/src/styles/styles.scss
- Sass added
- React bootstrapp added
- Header component started
=> Header Added & Style Setted up

client/src/components/footer/Footer.jsx
Inicio de modificacion de footer
=> refactor(client-footer):modificar sintaxis footer

README.md
Cambio de nombre en los autores del proyecto en el archivo readme
=> docs(readme): Change in author name

api/src/controllers/orderDetail/OrderDetail.controller.js, api/src/models/index.js, api/src/models/orderDetail/OrderDetail.model.js, api/src/routes/index.js, api/src/routes/orderDetail/orderDetail.routes.js, api/src/server.js
Creacion de ruta de orderDetail
=> feature(crear_rutas):crear ruta,model,controller

api/src/controllers/cart/Cart.controller.js, api/src/controllers/category/Category.controller.js, api/src/controllers/discount/Discount.controller.js, api/src/controllers/order/Order.controller.js, api/src/controllers/payment/Payment.controller.js, api/src/controllers/product/Product.controller.js, api/src/controllers/role/Role.controller.js, api/src/models/cart/Cart.model.js, api/src/models/cartProduct/CartProduct.model.js, api/src/models/codeDiscount/CodeDiscount.model.js, api/src/models/discount/Discount.model.js, api/src/models/index.js, api/src/models/orderDetail/OrderDetail.model.js, api/src/models/payment/Payment.model.js, api/src/models/product/Product.model.js, api/src/models/typeDiscount/TypeDiscount.model.js, api/src/routes/discount/discount.routes.js, api/src/routes/payment/payment.routes.js
Creacion de CRUD en los controladores
=> add(api, crud): Create crud in controllers

api/src/models/cart/Cart.model.js, api/src/models/index.js, api/src/models/order/Order.model.js, api/src/models/product/Product.model.js
Creacion de relacion de los modelos product, order, order_detail, category, cart, payment, cart_product, discount
=> add(api relation/model): Create relation for eight models

client/src/components/footer/Footer.jsx, client/src/components/main/Main.jsx, client/src/modules/detail/components/ProductDetail.jsx, client/src/modules/detail/components/ProductDetailMap.jsx, client/src/modules/drinkware/DrinkwareContainer.jsx, client/src/modules/drinkware/components/productDrinkware/ProductDrinkware.jsx, client/src/modules/drinkware/components/productDrinkware/ProductDrinkwareMap.jsx, client/src/modules/home/HomeContainer.jsx, client/src/modules/home/components/buyagain/BuyAgain.jsx, client/src/modules/home/components/buyagain/BuyAgainMap.jsx, client/src/modules/home/components/interestYou/InterestYou.jsx, client/src/modules/home/components/interestYou/InterestYouMap.jsx, client/src/modules/home/components/keepBuying/KeepBuying.jsx, client/src/modules/home/components/keepBuying/KeepBuyingMap.jsx, client/src/modules/home/components/reviewsClient/ReviewsClient.jsx, client/src/modules/home/components/reviewsClient/ReviewsClientMap.jsx, client/src/modules/home/components/warranty/Warranty.jsx, client/src/modules/shoppinCart/ShoppingCartContainer.jsx, client/src/modules/shoppinCart/components/listCart/ListCart.jsx, client/src/modules/shoppinCart/components/listCart/ListCartMap.jsx, client/src/modules/wishList/components/WishListMap.jsx, client/src/modules/wishList/components/WishListNameMap.jsx, client/src/modules/wishList/components/createModal/CreateModal.jsx, client/src/pages/Drinkware.jsx, client/src/pages/Home.jsx, client/src/routes/index.jsx, client/src/styles/abstracts/_mixins.scss, client/src/styles/base/_base.scss, client/src/styles/components/_footer.scss
Actualizacion de rutas de mockups
=> feature(routes-pages):crear-routes-pages

api/src/server.js, client/src/components/footer/Footer.jsx, client/src/modules/detail/components/ProductDetail.jsx, client/src/modules/shoppinCart/components/listCart/ListCart.jsx, client/src/modules/shoppinCart/components/listCart/ListCartMap.jsx, client/src/styles/abstracts/_mixins.scss, client/src/styles/components/_footer.scss
=> add(styles):add-styles

api/src/controllers/category/Category.controller.js, api/src/controllers/product/Product.controller.js, api/src/routes/product/product.routes.js
creacion de filter product-category
=> fix(api-filter): Create-filter-controller

api/src/controllers/discount/Discount.controller.js, api/src/controllers/order/Order.controller.js, api/src/controllers/product/Product.controller.js, api/src/controllers/user/User.controller.js, api/src/models/index.js, api/src/routes/discount/discount.routes.js, api/src/routes/product/product.routes.js
Correccion de filtrado de producto con descuento, ordenes de un producto y productos por categoria
=> fix(api-filter): Filter-product-order-discount-controllers

api/src/controllers/cart/Cart.controller.js, api/src/controllers/order/Order.controller.js, api/src/controllers/product/Product.controller.js, api/src/models/cartProduct/CartProduct.model.js, api/src/routes/cart/cart.routes.js, api/src/routes/order/order.routes.js, api/src/routes/product/product.routes.js
Se corrijieron algunas validaciones en los controladores, tambien cambio de nombre y reubicacion de los mismos
=> fix(api-controller): Validate queries in controllers

api/src/controllers/order/Order.controller.js, api/src/routes/order/order.routes.js
Creacion de controlador para el detalle de la orden del usuario, se corrigio bug en el controlador getOrdersByProduct
=> fix(fix-controller) add-controller-getOrderByUser

api/src/controllers/order/Order.controller.js, api/src/routes/order/order.routes.js, client/src/redux/service/review.service.jsx
Creacion de controladores deleteOrder-deleteProductOrder para las ordenes
=> fix(api-controllers): Create-deleteOrder-deleteProductOrder-controller

client/src/modules/shoppinCart/components/listCart/ListCart.jsx, client/src/styles/abstracts/_mixins.scss, client/src/styles/components/_shoppingCart.scss
=> feature(creacion-estilos):estilos-shop

client/src/modules/home/components/interestYou/InterestYouMap.jsx, client/src/modules/home/components/interestYou/InterestYouSwiper.jsx, client/src/styles/components/_reviews.scss
=> add/(update):swiper

client/src/components/header/Header.jsx, client/src/modules/ordersList/components/OrderList.jsx, client/src/modules/ordersList/components/order_admin_view/OrdernAdminView.jsx, client/src/modules/ordersList/components/order_admin_view/OrdernAdminViewMap.jsx, client/src/modules/ordersList/components/orders.js, client/src/modules/session/components/RegisterForm.jsx, client/src/styles/components/_order_list.scss
Ya se que no te gustan mis commits pero se me olvida como van 😆
=> Order detail modal created

client/src/modules/shoppinCart/components/listCart/ListCart.jsx, client/src/styles/base/_base.scss, client/src/styles/components/_shoppingCart.scss
=> add(styles):estilos

client/src/modules/detail/components/ProductDetail.jsx, client/src/styles/components/_product_detail.scss
=> Refactor(styles-somponents):refactorizacion_product_detail

client/src/modules/home/components/interestYou/InterestYouSwiper.jsx, client/src/styles/components/_interestYou.scss
Verificar en pantalla chica spaces
=> refactor(swiper):fixed-swiperToYou

client/src/styles/abstracts/_mixins.scss, client/src/styles/components/_shoppingCart.scss
=> fixed(querys-cart):ready-querys-cart
